// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// Source: commerce/coupon.repository.extended.proto
/* eslint-disable */

import type { ByteSource, PartialDeep } from "protoscript";
import * as protoscript from "protoscript";
import { JSONrequest, PBrequest } from "twirpscript";
// This is the minimum version supported by the current runtime.
// If this line fails typechecking, breaking changes have been introduced and this
// file needs to be regenerated by running `npx twirpscript`.
export { MIN_SUPPORTED_VERSION_0_0_56 } from "twirpscript";
import type { ClientConfiguration } from "twirpscript";
import * as commerceCoupon from "./coupon.pb";

//========================================//
//                 Types                  //
//========================================//

export interface GetCouponByCodeRequest {
  code: string;
}

//==========================================//
// CouponRepositoryExtended Protobuf Client //
//==========================================//

export async function GetCouponByCode(
  getCouponByCodeRequest: GetCouponByCodeRequest,
  config?: ClientConfiguration,
): Promise<commerceCoupon.Coupon> {
  const response = await PBrequest(
    "/commerce.CouponRepositoryExtended/GetCouponByCode",
    GetCouponByCodeRequest.encode(getCouponByCodeRequest),
    config,
  );
  return commerceCoupon.Coupon.decode(response);
}

//========================================//
//  CouponRepositoryExtended JSON Client  //
//========================================//

export async function GetCouponByCodeJSON(
  getCouponByCodeRequest: GetCouponByCodeRequest,
  config?: ClientConfiguration,
): Promise<commerceCoupon.Coupon> {
  const response = await JSONrequest(
    "/commerce.CouponRepositoryExtended/GetCouponByCode",
    GetCouponByCodeRequestJSON.encode(getCouponByCodeRequest),
    config,
  );
  return commerceCoupon.CouponJSON.decode(response);
}

//========================================//
//        CouponRepositoryExtended        //
//========================================//

/**
 *
 * CouponRepositoryExtended adds more methods to the CouponRepository.
 */
export interface CouponRepositoryExtended<Context = unknown> {
  GetCouponByCode: (
    getCouponByCodeRequest: GetCouponByCodeRequest,
    context: Context,
  ) => Promise<commerceCoupon.Coupon> | commerceCoupon.Coupon;
}

export function createCouponRepositoryExtended<Context>(
  service: CouponRepositoryExtended<Context>,
) {
  return {
    name: "commerce.CouponRepositoryExtended",
    methods: {
      GetCouponByCode: {
        name: "GetCouponByCode",
        handler: service.GetCouponByCode,
        input: {
          protobuf: GetCouponByCodeRequest,
          json: GetCouponByCodeRequestJSON,
        },
        output: {
          protobuf: commerceCoupon.Coupon,
          json: commerceCoupon.CouponJSON,
        },
      },
    },
  } as const;
}

//========================================//
//        Protobuf Encode / Decode        //
//========================================//

export const GetCouponByCodeRequest = {
  /**
   * Serializes GetCouponByCodeRequest to protobuf.
   */
  encode: function (msg: PartialDeep<GetCouponByCodeRequest>): Uint8Array {
    return GetCouponByCodeRequest._writeMessage(
      msg,
      new protoscript.BinaryWriter(),
    ).getResultBuffer();
  },

  /**
   * Deserializes GetCouponByCodeRequest from protobuf.
   */
  decode: function (bytes: ByteSource): GetCouponByCodeRequest {
    return GetCouponByCodeRequest._readMessage(
      GetCouponByCodeRequest.initialize(),
      new protoscript.BinaryReader(bytes),
    );
  },

  /**
   * Initializes GetCouponByCodeRequest with all fields set to their default value.
   */
  initialize: function (
    msg?: Partial<GetCouponByCodeRequest>,
  ): GetCouponByCodeRequest {
    return {
      code: "",
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<GetCouponByCodeRequest>,
    writer: protoscript.BinaryWriter,
  ): protoscript.BinaryWriter {
    if (msg.code) {
      writer.writeString(1, msg.code);
    }
    return writer;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: GetCouponByCodeRequest,
    reader: protoscript.BinaryReader,
  ): GetCouponByCodeRequest {
    while (reader.nextField()) {
      const field = reader.getFieldNumber();
      switch (field) {
        case 1: {
          msg.code = reader.readString();
          break;
        }
        default: {
          reader.skipField();
          break;
        }
      }
    }
    return msg;
  },
};

//========================================//
//          JSON Encode / Decode          //
//========================================//

export const GetCouponByCodeRequestJSON = {
  /**
   * Serializes GetCouponByCodeRequest to JSON.
   */
  encode: function (msg: PartialDeep<GetCouponByCodeRequest>): string {
    return JSON.stringify(GetCouponByCodeRequestJSON._writeMessage(msg));
  },

  /**
   * Deserializes GetCouponByCodeRequest from JSON.
   */
  decode: function (json: string): GetCouponByCodeRequest {
    return GetCouponByCodeRequestJSON._readMessage(
      GetCouponByCodeRequestJSON.initialize(),
      JSON.parse(json),
    );
  },

  /**
   * Initializes GetCouponByCodeRequest with all fields set to their default value.
   */
  initialize: function (
    msg?: Partial<GetCouponByCodeRequest>,
  ): GetCouponByCodeRequest {
    return {
      code: "",
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<GetCouponByCodeRequest>,
  ): Record<string, unknown> {
    const json: Record<string, unknown> = {};
    if (msg.code) {
      json["code"] = msg.code;
    }
    return json;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: GetCouponByCodeRequest,
    json: any,
  ): GetCouponByCodeRequest {
    const _code_ = json["code"];
    if (_code_) {
      msg.code = _code_;
    }
    return msg;
  },
};
