// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// Source: workshop/contact.service.proto
/* eslint-disable */

import type { ByteSource, PartialDeep } from "protoscript";
import * as protoscript from "protoscript";
import { JSONrequest, PBrequest } from "twirpscript";
// This is the minimum version supported by the current runtime.
// If this line fails typechecking, breaking changes have been introduced and this
// file needs to be regenerated by running `npx twirpscript`.
export { MIN_SUPPORTED_VERSION_0_0_56 } from "twirpscript";
import type { ClientConfiguration } from "twirpscript";

//========================================//
//                 Types                  //
//========================================//

export interface SubmitInquiryRequest {
  customer: Customer;
}

export interface SubmitInquiryResponse {
  message: string;
}

export interface Customer {
  firstName: string;
  lastName: string;
  email: string;
  contactNumber: string;
  interests: string[];
  message: string;
  newsletter: boolean;
}

//========================================//
//     ContactService Protobuf Client     //
//========================================//

/**
 * Contact us will be a service to manage contact us form submissions
 */
export async function SubmitInquiry(
  submitInquiryRequest: SubmitInquiryRequest,
  config?: ClientConfiguration,
): Promise<SubmitInquiryResponse> {
  const response = await PBrequest(
    "/workshop.ContactService/SubmitInquiry",
    SubmitInquiryRequest.encode(submitInquiryRequest),
    config,
  );
  return SubmitInquiryResponse.decode(response);
}

//========================================//
//       ContactService JSON Client       //
//========================================//

/**
 * Contact us will be a service to manage contact us form submissions
 */
export async function SubmitInquiryJSON(
  submitInquiryRequest: SubmitInquiryRequest,
  config?: ClientConfiguration,
): Promise<SubmitInquiryResponse> {
  const response = await JSONrequest(
    "/workshop.ContactService/SubmitInquiry",
    SubmitInquiryRequestJSON.encode(submitInquiryRequest),
    config,
  );
  return SubmitInquiryResponseJSON.decode(response);
}

//========================================//
//             ContactService             //
//========================================//

export interface ContactService<Context = unknown> {
  /**
   * Contact us will be a service to manage contact us form submissions
   */
  SubmitInquiry: (
    submitInquiryRequest: SubmitInquiryRequest,
    context: Context,
  ) => Promise<SubmitInquiryResponse> | SubmitInquiryResponse;
}

export function createContactService<Context>(
  service: ContactService<Context>,
) {
  return {
    name: "workshop.ContactService",
    methods: {
      SubmitInquiry: {
        name: "SubmitInquiry",
        handler: service.SubmitInquiry,
        input: {
          protobuf: SubmitInquiryRequest,
          json: SubmitInquiryRequestJSON,
        },
        output: {
          protobuf: SubmitInquiryResponse,
          json: SubmitInquiryResponseJSON,
        },
      },
    },
  } as const;
}

//========================================//
//        Protobuf Encode / Decode        //
//========================================//

export const SubmitInquiryRequest = {
  /**
   * Serializes SubmitInquiryRequest to protobuf.
   */
  encode: function (msg: PartialDeep<SubmitInquiryRequest>): Uint8Array {
    return SubmitInquiryRequest._writeMessage(
      msg,
      new protoscript.BinaryWriter(),
    ).getResultBuffer();
  },

  /**
   * Deserializes SubmitInquiryRequest from protobuf.
   */
  decode: function (bytes: ByteSource): SubmitInquiryRequest {
    return SubmitInquiryRequest._readMessage(
      SubmitInquiryRequest.initialize(),
      new protoscript.BinaryReader(bytes),
    );
  },

  /**
   * Initializes SubmitInquiryRequest with all fields set to their default value.
   */
  initialize: function (
    msg?: Partial<SubmitInquiryRequest>,
  ): SubmitInquiryRequest {
    return {
      customer: Customer.initialize(),
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<SubmitInquiryRequest>,
    writer: protoscript.BinaryWriter,
  ): protoscript.BinaryWriter {
    if (msg.customer) {
      writer.writeMessage(1, msg.customer, Customer._writeMessage);
    }
    return writer;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: SubmitInquiryRequest,
    reader: protoscript.BinaryReader,
  ): SubmitInquiryRequest {
    while (reader.nextField()) {
      const field = reader.getFieldNumber();
      switch (field) {
        case 1: {
          reader.readMessage(msg.customer, Customer._readMessage);
          break;
        }
        default: {
          reader.skipField();
          break;
        }
      }
    }
    return msg;
  },
};

export const SubmitInquiryResponse = {
  /**
   * Serializes SubmitInquiryResponse to protobuf.
   */
  encode: function (msg: PartialDeep<SubmitInquiryResponse>): Uint8Array {
    return SubmitInquiryResponse._writeMessage(
      msg,
      new protoscript.BinaryWriter(),
    ).getResultBuffer();
  },

  /**
   * Deserializes SubmitInquiryResponse from protobuf.
   */
  decode: function (bytes: ByteSource): SubmitInquiryResponse {
    return SubmitInquiryResponse._readMessage(
      SubmitInquiryResponse.initialize(),
      new protoscript.BinaryReader(bytes),
    );
  },

  /**
   * Initializes SubmitInquiryResponse with all fields set to their default value.
   */
  initialize: function (
    msg?: Partial<SubmitInquiryResponse>,
  ): SubmitInquiryResponse {
    return {
      message: "",
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<SubmitInquiryResponse>,
    writer: protoscript.BinaryWriter,
  ): protoscript.BinaryWriter {
    if (msg.message) {
      writer.writeString(1, msg.message);
    }
    return writer;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: SubmitInquiryResponse,
    reader: protoscript.BinaryReader,
  ): SubmitInquiryResponse {
    while (reader.nextField()) {
      const field = reader.getFieldNumber();
      switch (field) {
        case 1: {
          msg.message = reader.readString();
          break;
        }
        default: {
          reader.skipField();
          break;
        }
      }
    }
    return msg;
  },
};

export const Customer = {
  /**
   * Serializes Customer to protobuf.
   */
  encode: function (msg: PartialDeep<Customer>): Uint8Array {
    return Customer._writeMessage(
      msg,
      new protoscript.BinaryWriter(),
    ).getResultBuffer();
  },

  /**
   * Deserializes Customer from protobuf.
   */
  decode: function (bytes: ByteSource): Customer {
    return Customer._readMessage(
      Customer.initialize(),
      new protoscript.BinaryReader(bytes),
    );
  },

  /**
   * Initializes Customer with all fields set to their default value.
   */
  initialize: function (msg?: Partial<Customer>): Customer {
    return {
      firstName: "",
      lastName: "",
      email: "",
      contactNumber: "",
      interests: [],
      message: "",
      newsletter: false,
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<Customer>,
    writer: protoscript.BinaryWriter,
  ): protoscript.BinaryWriter {
    if (msg.firstName) {
      writer.writeString(1, msg.firstName);
    }
    if (msg.lastName) {
      writer.writeString(2, msg.lastName);
    }
    if (msg.email) {
      writer.writeString(3, msg.email);
    }
    if (msg.contactNumber) {
      writer.writeString(4, msg.contactNumber);
    }
    if (msg.interests?.length) {
      writer.writeRepeatedString(5, msg.interests);
    }
    if (msg.message) {
      writer.writeString(6, msg.message);
    }
    if (msg.newsletter) {
      writer.writeBool(7, msg.newsletter);
    }
    return writer;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: Customer,
    reader: protoscript.BinaryReader,
  ): Customer {
    while (reader.nextField()) {
      const field = reader.getFieldNumber();
      switch (field) {
        case 1: {
          msg.firstName = reader.readString();
          break;
        }
        case 2: {
          msg.lastName = reader.readString();
          break;
        }
        case 3: {
          msg.email = reader.readString();
          break;
        }
        case 4: {
          msg.contactNumber = reader.readString();
          break;
        }
        case 5: {
          msg.interests.push(reader.readString());
          break;
        }
        case 6: {
          msg.message = reader.readString();
          break;
        }
        case 7: {
          msg.newsletter = reader.readBool();
          break;
        }
        default: {
          reader.skipField();
          break;
        }
      }
    }
    return msg;
  },
};

//========================================//
//          JSON Encode / Decode          //
//========================================//

export const SubmitInquiryRequestJSON = {
  /**
   * Serializes SubmitInquiryRequest to JSON.
   */
  encode: function (msg: PartialDeep<SubmitInquiryRequest>): string {
    return JSON.stringify(SubmitInquiryRequestJSON._writeMessage(msg));
  },

  /**
   * Deserializes SubmitInquiryRequest from JSON.
   */
  decode: function (json: string): SubmitInquiryRequest {
    return SubmitInquiryRequestJSON._readMessage(
      SubmitInquiryRequestJSON.initialize(),
      JSON.parse(json),
    );
  },

  /**
   * Initializes SubmitInquiryRequest with all fields set to their default value.
   */
  initialize: function (
    msg?: Partial<SubmitInquiryRequest>,
  ): SubmitInquiryRequest {
    return {
      customer: CustomerJSON.initialize(),
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<SubmitInquiryRequest>,
  ): Record<string, unknown> {
    const json: Record<string, unknown> = {};
    if (msg.customer) {
      const _customer_ = CustomerJSON._writeMessage(msg.customer);
      if (Object.keys(_customer_).length > 0) {
        json["customer"] = _customer_;
      }
    }
    return json;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: SubmitInquiryRequest,
    json: any,
  ): SubmitInquiryRequest {
    const _customer_ = json["customer"];
    if (_customer_) {
      CustomerJSON._readMessage(msg.customer, _customer_);
    }
    return msg;
  },
};

export const SubmitInquiryResponseJSON = {
  /**
   * Serializes SubmitInquiryResponse to JSON.
   */
  encode: function (msg: PartialDeep<SubmitInquiryResponse>): string {
    return JSON.stringify(SubmitInquiryResponseJSON._writeMessage(msg));
  },

  /**
   * Deserializes SubmitInquiryResponse from JSON.
   */
  decode: function (json: string): SubmitInquiryResponse {
    return SubmitInquiryResponseJSON._readMessage(
      SubmitInquiryResponseJSON.initialize(),
      JSON.parse(json),
    );
  },

  /**
   * Initializes SubmitInquiryResponse with all fields set to their default value.
   */
  initialize: function (
    msg?: Partial<SubmitInquiryResponse>,
  ): SubmitInquiryResponse {
    return {
      message: "",
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<SubmitInquiryResponse>,
  ): Record<string, unknown> {
    const json: Record<string, unknown> = {};
    if (msg.message) {
      json["message"] = msg.message;
    }
    return json;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: SubmitInquiryResponse,
    json: any,
  ): SubmitInquiryResponse {
    const _message_ = json["message"];
    if (_message_) {
      msg.message = _message_;
    }
    return msg;
  },
};

export const CustomerJSON = {
  /**
   * Serializes Customer to JSON.
   */
  encode: function (msg: PartialDeep<Customer>): string {
    return JSON.stringify(CustomerJSON._writeMessage(msg));
  },

  /**
   * Deserializes Customer from JSON.
   */
  decode: function (json: string): Customer {
    return CustomerJSON._readMessage(
      CustomerJSON.initialize(),
      JSON.parse(json),
    );
  },

  /**
   * Initializes Customer with all fields set to their default value.
   */
  initialize: function (msg?: Partial<Customer>): Customer {
    return {
      firstName: "",
      lastName: "",
      email: "",
      contactNumber: "",
      interests: [],
      message: "",
      newsletter: false,
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<Customer>,
  ): Record<string, unknown> {
    const json: Record<string, unknown> = {};
    if (msg.firstName) {
      json["firstName"] = msg.firstName;
    }
    if (msg.lastName) {
      json["lastName"] = msg.lastName;
    }
    if (msg.email) {
      json["email"] = msg.email;
    }
    if (msg.contactNumber) {
      json["contactNumber"] = msg.contactNumber;
    }
    if (msg.interests?.length) {
      json["interests"] = msg.interests;
    }
    if (msg.message) {
      json["message"] = msg.message;
    }
    if (msg.newsletter) {
      json["newsletter"] = msg.newsletter;
    }
    return json;
  },

  /**
   * @private
   */
  _readMessage: function (msg: Customer, json: any): Customer {
    const _firstName_ = json["firstName"];
    if (_firstName_) {
      msg.firstName = _firstName_;
    }
    const _lastName_ = json["lastName"];
    if (_lastName_) {
      msg.lastName = _lastName_;
    }
    const _email_ = json["email"];
    if (_email_) {
      msg.email = _email_;
    }
    const _contactNumber_ = json["contactNumber"];
    if (_contactNumber_) {
      msg.contactNumber = _contactNumber_;
    }
    const _interests_ = json["interests"];
    if (_interests_) {
      msg.interests = _interests_;
    }
    const _message_ = json["message"];
    if (_message_) {
      msg.message = _message_;
    }
    const _newsletter_ = json["newsletter"];
    if (_newsletter_) {
      msg.newsletter = _newsletter_;
    }
    return msg;
  },
};
