// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// Source: billing/invoice.service.proto
/* eslint-disable */

import type { ByteSource, PartialDeep } from "protoscript";
import * as protoscript from "protoscript";
import { JSONrequest, PBrequest } from "twirpscript";
// This is the minimum version supported by the current runtime.
// If this line fails typechecking, breaking changes have been introduced and this
// file needs to be regenerated by running `npx twirpscript`.
export { MIN_SUPPORTED_VERSION_0_0_56 } from "twirpscript";
import type { ClientConfiguration } from "twirpscript";

//========================================//
//                 Types                  //
//========================================//

export interface GenerateInvoiceRequest {
  order: string;
}

export interface GenerateInvoiceResponse {
  url: string;
}

//========================================//
//     InvoiceService Protobuf Client     //
//========================================//

/**
 * GenerateInvoice will generate a PDF invoice and upload it to cloud storage.
 * The invoice can be downloaded using the URL provided in the response.
 * If an invoice already exists for the order, no new invoice will be generated,
 * but the existing invoice URL will be returned.
 */
export async function GenerateInvoice(
  generateInvoiceRequest: GenerateInvoiceRequest,
  config?: ClientConfiguration,
): Promise<GenerateInvoiceResponse> {
  const response = await PBrequest(
    "/billing.InvoiceService/GenerateInvoice",
    GenerateInvoiceRequest.encode(generateInvoiceRequest),
    config,
  );
  return GenerateInvoiceResponse.decode(response);
}

/**
 * GenerateMyInvoice should ensure the given order belongs to the authenticated user, and under the hood call GenerateInvoice.
 */
export async function GenerateMyInvoice(
  generateInvoiceRequest: GenerateInvoiceRequest,
  config?: ClientConfiguration,
): Promise<GenerateInvoiceResponse> {
  const response = await PBrequest(
    "/billing.InvoiceService/GenerateMyInvoice",
    GenerateInvoiceRequest.encode(generateInvoiceRequest),
    config,
  );
  return GenerateInvoiceResponse.decode(response);
}

//========================================//
//       InvoiceService JSON Client       //
//========================================//

/**
 * GenerateInvoice will generate a PDF invoice and upload it to cloud storage.
 * The invoice can be downloaded using the URL provided in the response.
 * If an invoice already exists for the order, no new invoice will be generated,
 * but the existing invoice URL will be returned.
 */
export async function GenerateInvoiceJSON(
  generateInvoiceRequest: GenerateInvoiceRequest,
  config?: ClientConfiguration,
): Promise<GenerateInvoiceResponse> {
  const response = await JSONrequest(
    "/billing.InvoiceService/GenerateInvoice",
    GenerateInvoiceRequestJSON.encode(generateInvoiceRequest),
    config,
  );
  return GenerateInvoiceResponseJSON.decode(response);
}

/**
 * GenerateMyInvoice should ensure the given order belongs to the authenticated user, and under the hood call GenerateInvoice.
 */
export async function GenerateMyInvoiceJSON(
  generateInvoiceRequest: GenerateInvoiceRequest,
  config?: ClientConfiguration,
): Promise<GenerateInvoiceResponse> {
  const response = await JSONrequest(
    "/billing.InvoiceService/GenerateMyInvoice",
    GenerateInvoiceRequestJSON.encode(generateInvoiceRequest),
    config,
  );
  return GenerateInvoiceResponseJSON.decode(response);
}

//========================================//
//             InvoiceService             //
//========================================//

export interface InvoiceService<Context = unknown> {
  /**
   * GenerateInvoice will generate a PDF invoice and upload it to cloud storage.
   * The invoice can be downloaded using the URL provided in the response.
   * If an invoice already exists for the order, no new invoice will be generated,
   * but the existing invoice URL will be returned.
   */
  GenerateInvoice: (
    generateInvoiceRequest: GenerateInvoiceRequest,
    context: Context,
  ) => Promise<GenerateInvoiceResponse> | GenerateInvoiceResponse;
  /**
   * GenerateMyInvoice should ensure the given order belongs to the authenticated user, and under the hood call GenerateInvoice.
   */
  GenerateMyInvoice: (
    generateInvoiceRequest: GenerateInvoiceRequest,
    context: Context,
  ) => Promise<GenerateInvoiceResponse> | GenerateInvoiceResponse;
}

export function createInvoiceService<Context>(
  service: InvoiceService<Context>,
) {
  return {
    name: "billing.InvoiceService",
    methods: {
      GenerateInvoice: {
        name: "GenerateInvoice",
        handler: service.GenerateInvoice,
        input: {
          protobuf: GenerateInvoiceRequest,
          json: GenerateInvoiceRequestJSON,
        },
        output: {
          protobuf: GenerateInvoiceResponse,
          json: GenerateInvoiceResponseJSON,
        },
      },
      GenerateMyInvoice: {
        name: "GenerateMyInvoice",
        handler: service.GenerateMyInvoice,
        input: {
          protobuf: GenerateInvoiceRequest,
          json: GenerateInvoiceRequestJSON,
        },
        output: {
          protobuf: GenerateInvoiceResponse,
          json: GenerateInvoiceResponseJSON,
        },
      },
    },
  } as const;
}

//========================================//
//        Protobuf Encode / Decode        //
//========================================//

export const GenerateInvoiceRequest = {
  /**
   * Serializes GenerateInvoiceRequest to protobuf.
   */
  encode: function (msg: PartialDeep<GenerateInvoiceRequest>): Uint8Array {
    return GenerateInvoiceRequest._writeMessage(
      msg,
      new protoscript.BinaryWriter(),
    ).getResultBuffer();
  },

  /**
   * Deserializes GenerateInvoiceRequest from protobuf.
   */
  decode: function (bytes: ByteSource): GenerateInvoiceRequest {
    return GenerateInvoiceRequest._readMessage(
      GenerateInvoiceRequest.initialize(),
      new protoscript.BinaryReader(bytes),
    );
  },

  /**
   * Initializes GenerateInvoiceRequest with all fields set to their default value.
   */
  initialize: function (
    msg?: Partial<GenerateInvoiceRequest>,
  ): GenerateInvoiceRequest {
    return {
      order: "",
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<GenerateInvoiceRequest>,
    writer: protoscript.BinaryWriter,
  ): protoscript.BinaryWriter {
    if (msg.order) {
      writer.writeString(1, msg.order);
    }
    return writer;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: GenerateInvoiceRequest,
    reader: protoscript.BinaryReader,
  ): GenerateInvoiceRequest {
    while (reader.nextField()) {
      const field = reader.getFieldNumber();
      switch (field) {
        case 1: {
          msg.order = reader.readString();
          break;
        }
        default: {
          reader.skipField();
          break;
        }
      }
    }
    return msg;
  },
};

export const GenerateInvoiceResponse = {
  /**
   * Serializes GenerateInvoiceResponse to protobuf.
   */
  encode: function (msg: PartialDeep<GenerateInvoiceResponse>): Uint8Array {
    return GenerateInvoiceResponse._writeMessage(
      msg,
      new protoscript.BinaryWriter(),
    ).getResultBuffer();
  },

  /**
   * Deserializes GenerateInvoiceResponse from protobuf.
   */
  decode: function (bytes: ByteSource): GenerateInvoiceResponse {
    return GenerateInvoiceResponse._readMessage(
      GenerateInvoiceResponse.initialize(),
      new protoscript.BinaryReader(bytes),
    );
  },

  /**
   * Initializes GenerateInvoiceResponse with all fields set to their default value.
   */
  initialize: function (
    msg?: Partial<GenerateInvoiceResponse>,
  ): GenerateInvoiceResponse {
    return {
      url: "",
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<GenerateInvoiceResponse>,
    writer: protoscript.BinaryWriter,
  ): protoscript.BinaryWriter {
    if (msg.url) {
      writer.writeString(1, msg.url);
    }
    return writer;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: GenerateInvoiceResponse,
    reader: protoscript.BinaryReader,
  ): GenerateInvoiceResponse {
    while (reader.nextField()) {
      const field = reader.getFieldNumber();
      switch (field) {
        case 1: {
          msg.url = reader.readString();
          break;
        }
        default: {
          reader.skipField();
          break;
        }
      }
    }
    return msg;
  },
};

//========================================//
//          JSON Encode / Decode          //
//========================================//

export const GenerateInvoiceRequestJSON = {
  /**
   * Serializes GenerateInvoiceRequest to JSON.
   */
  encode: function (msg: PartialDeep<GenerateInvoiceRequest>): string {
    return JSON.stringify(GenerateInvoiceRequestJSON._writeMessage(msg));
  },

  /**
   * Deserializes GenerateInvoiceRequest from JSON.
   */
  decode: function (json: string): GenerateInvoiceRequest {
    return GenerateInvoiceRequestJSON._readMessage(
      GenerateInvoiceRequestJSON.initialize(),
      JSON.parse(json),
    );
  },

  /**
   * Initializes GenerateInvoiceRequest with all fields set to their default value.
   */
  initialize: function (
    msg?: Partial<GenerateInvoiceRequest>,
  ): GenerateInvoiceRequest {
    return {
      order: "",
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<GenerateInvoiceRequest>,
  ): Record<string, unknown> {
    const json: Record<string, unknown> = {};
    if (msg.order) {
      json["order"] = msg.order;
    }
    return json;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: GenerateInvoiceRequest,
    json: any,
  ): GenerateInvoiceRequest {
    const _order_ = json["order"];
    if (_order_) {
      msg.order = _order_;
    }
    return msg;
  },
};

export const GenerateInvoiceResponseJSON = {
  /**
   * Serializes GenerateInvoiceResponse to JSON.
   */
  encode: function (msg: PartialDeep<GenerateInvoiceResponse>): string {
    return JSON.stringify(GenerateInvoiceResponseJSON._writeMessage(msg));
  },

  /**
   * Deserializes GenerateInvoiceResponse from JSON.
   */
  decode: function (json: string): GenerateInvoiceResponse {
    return GenerateInvoiceResponseJSON._readMessage(
      GenerateInvoiceResponseJSON.initialize(),
      JSON.parse(json),
    );
  },

  /**
   * Initializes GenerateInvoiceResponse with all fields set to their default value.
   */
  initialize: function (
    msg?: Partial<GenerateInvoiceResponse>,
  ): GenerateInvoiceResponse {
    return {
      url: "",
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<GenerateInvoiceResponse>,
  ): Record<string, unknown> {
    const json: Record<string, unknown> = {};
    if (msg.url) {
      json["url"] = msg.url;
    }
    return json;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: GenerateInvoiceResponse,
    json: any,
  ): GenerateInvoiceResponse {
    const _url_ = json["url"];
    if (_url_) {
      msg.url = _url_;
    }
    return msg;
  },
};
